### ISSUE TITLE
Maintenance/Inner workings question

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-game-mods/player_api#1]
Sorry for opening an issue here :confounded: 

How reliable are those repositories and how does that work exactly?
I haven't found any project-links here...

**Comment by tacotexmex** [comment]
Long time. https://github.com/tacotexmex/maki is what runs it, but the machine it runs on appears to have some issues. You can run it locally If you'd like.

**Comment by BuckarooBanzay** [comment]
uh, thanks for the response but i've implemented it myself here in the meantime: https://github.com/minetest-game

**Comment by tacotexmex** [comment]
Heh, and a nicer implementation at that. :)
